### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by maxpolun**
The dependencies were failing `npm audit`, so I went and updated them (and fixed a jest error by updating to the latest version too).

### CODE REVIEW

**Comment by scottned** [comment]
Please merge and publish this PR.  Growl 1.9.0 (a transitive dependency) is considered a critical security issue.

**Review by ReadyPlayerNaN — APPROVED** [review]

**Comment by ReadyPlayerNaN** [comment]
@lgandecki, is this project abandoned?

**Comment by lgandecki** [comment]
Thanks for the reminder! Let me take a look at this PR tomorrow when Im in front of a computer. sorry for the delay

**Comment by lgandecki** [comment]
published, thanks!

**Pull request merged**
